### ISSUE TITLE
Version 3.3.0 doesn't seem to be available on ansible galaxy

### ISSUE THREAD

**Issue by mherold** [hifis-net/ansible-collection-toolkit#201]
Same problem (and workaround) as in #169? 😢

**Comment by mherold** [comment]
I just noticed, the version is not available in https://galaxy.ansible.com/ui/standalone/roles/hifis/unattended_upgrades/. but there's another role that seems to have been published recently, but with a hyphen instead of an underscore (which does contain v3.3.0): https://galaxy.ansible.com/ui/standalone/roles/hifis/unattended-upgrades/

**Comment by tobiashuste** [comment]
Thanks for the hint. This is indeed strange.

We'll check and keep you updated once we figured out what's happening.

**Comment by tobiashuste** [comment]
Somehow this is related to the changes made to the previous and next generation Ansible Galaxy. It is not very clear, what's going on, at least for us. We also have no real clue how to fix it.

Since the support for roles seems not to be priority 1 in Ansible, we are about to change the role into a collection and will provide instructions on how to convert from the role to a collection.
With this change, also new versions will properly appear again. We hope that this will be the most practicable solution for all parties. See also #198 and this branch https://github.com/hifis-net/ansible-role-unattended-upgrades/tree/release-version-4.0.0.

**Comment by Normo** [comment]
@mherold @shadow1runner Feel free to switch to the [`hifis.toolkit` collection](https://galaxy.ansible.com/ui/repo/published/hifis/toolkit/):
```sh
ansible-galaxy collection install hifis.toolkit
```

```yaml
- hosts: all
  roles:
     - role: hifis.toolkit.unattended_upgrades
```
